version: "3.8"

services:
    sessions_management_service-container:
        image: ghcr.io/userver-framework/ubuntu-userver-build-base:v2
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/sessions_management_service/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
          - CMAKE_COMMON_FLAGS
        volumes:
          - .:/sessions_management_service:rw
          - ./third_party/userver/tools/docker:/tools:ro
        ports:
          - 8080:8080
        working_dir: /sessions_management_service
        entrypoint:
          - /tools/run_as_user.sh
